use super::{CommandGroup, CommandSpec, spec};

pub const COMMANDS: &[CommandSpec] = &[
    spec(
        "device",
        "<login|logout|list>",
        "Device authentication and management",
        CommandGroup::Account,
        false,
        false,
        false,
    ),
    spec(
        "relay",
        "<list>",
        "List active relay sessions for your account",
        CommandGroup::Account,
        false,
        false,
        false,
    ),
    spec(
        "totp",
        "<subcommand>",
        "Manage stored TOTP secrets",
        CommandGroup::Account,
        false,
        false,
        false,
    ),
    spec(
        "hotp",
        "<add|get|list|show|counter|remove>",
        "Manage counter-based (HOTP) secrets, e.g. Duo",
        CommandGroup::Account,
        false,
        false,
        false,
    ),
    spec(
        "duo",
        "enroll <service> <account> <activation-url>",
        "Capture a Duo Mobile activation into the HOTP store",
        CommandGroup::Account,
        false,
        false,
        false,
    ),
    spec(
        "kv",
        "<set|get|list|delete|tag|history|rollback|exec>",
        "Encrypted KV store with tags, versioning, and secret exec",
        CommandGroup::Account,
        false,
        false,
        false,
    ),
];
