use super::{CommandGroup, CommandSpec, spec};

pub const COMMANDS: &[CommandSpec] = &[
    spec(
        "proxy",
        "<log|show|clear> [--last=N]",
        "View captured proxy request/response payloads",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "repl",
        "[-c <credential>] [-m <model>] [-p <prompt>] [-r [session_id]] [--verbose]",
        "Interactive LLM agent with credential, model, and session controls",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "bus",
        "<who|requests|replies|show|send|done> [args]",
        "Agent bus subcommands",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "memory",
        "<write|search|context|observe|sessions|compact|patterns|rate|detail|history> ...",
        "Local agent memory on SQLite",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "journal",
        "<list|show> [args]",
        "Inspect REPL session journals (read-only)",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "tasks",
        "<add|list|done|reopen|delete|show|depend|undepend|deps> ...",
        "Local task list with SQLite-backed dependencies",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "agent-sessions",
        "[show|rename|note] [args] [--limit=N] [--active] [--project=<name>|--all-projects]",
        "Inspect local Sidekar agent session history",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "repo",
        "<pack|tree> [args]",
        "Pack repos and show repo trees with token estimates",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "compact",
        "<classify|filter|run> ...",
        "Compact noisy command output for agent use",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "monitor",
        "<start|stop|status>",
        "Watch tabs for background changes",
        CommandGroup::Agent,
        true,
        true,
        false,
    ),
    spec(
        "cron",
        "<create|list|show|delete> [args]",
        "Scheduled job subcommands",
        CommandGroup::Jobs,
        false,
        false,
        false,
    ),
    spec(
        "loop",
        "<interval> <prompt_or_command>",
        "Run a prompt on a recurring interval (e.g. loop 5m \"check status\")",
        CommandGroup::Jobs,
        false,
        false,
        false,
    ),
];
