use super::{CommandGroup, CommandSpec, spec};

pub const COMMANDS: &[CommandSpec] = &[
    spec(
        "google",
        "<login|status|logout>",
        "Google Workspace account for Gmail/Drive/Calendar",
        CommandGroup::Account,
        false,
        false,
        false,
    ),
    spec(
        "gmail",
        "<search|read|send|draft|attachments|attachment|labels|modify> [args...]",
        "Gmail over the API",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "drive",
        "<ls|get|put> [args...]",
        "Google Drive over the API",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "calendar",
        "<list|create> [args...]",
        "Google Calendar over the API",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "sheets",
        "<info|get|set|append|create> [args...]",
        "Google Sheets over the API",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "docs",
        "<get|title|create|append|replace> [args...]",
        "Google Docs over the API",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "spawn",
        "<agent> [task] [--nick <name>] [--cwd <dir>] [--model <m>] [--no-yolo] | list",
        "Launch another agent on the bus and print its name",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "stop",
        "<agent-name> [--force]",
        "Stop an agent started by sidekar spawn",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "proxy",
        "<log|show|clear> [--last=N]",
        "View captured proxy request/response payloads",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "repl",
        "[-c <credential>] [-m <model>] [-p <prompt>] [-r [session_id]] [--verbose]",
        "Interactive LLM agent with credential, model, and session controls",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "bus",
        "<who|requests|replies|show|send|done|cancel> [args]",
        "Agent bus subcommands",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "memory",
        "<write|search|context|observe|sessions|compact|patterns|rate|detail|history|import> ...",
        "Local agent memory on SQLite",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "journal",
        "<list|show> [args]",
        "Inspect REPL session journals (read-only)",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "tasks",
        "<add|list|done|reopen|delete|show|depend|undepend|deps> ...",
        "Local task list with SQLite-backed dependencies",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "agent-sessions",
        "[show|rename|note] [args] [--limit=N] [--active] [--project=<name>|--all-projects]",
        "Inspect local Sidekar agent session history",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "repo",
        "<pack|tree> [args]",
        "Pack repos and show repo trees with token estimates",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "compact",
        "<classify|filter|run> ...",
        "Compact noisy command output for agent use",
        CommandGroup::Agent,
        false,
        false,
        false,
    ),
    spec(
        "monitor",
        "<start|stop|status> [tab_id|all]",
        "CDP tabs → bus; in REPL use Sidekar tool not Bash (see tool doc \"Tab monitor\")",
        CommandGroup::Agent,
        true,
        true,
        false,
    ),
    spec(
        "cron",
        "<create|list|show|delete> [args]",
        "Scheduled job subcommands",
        CommandGroup::Jobs,
        false,
        false,
        false,
    ),
    spec(
        "loop",
        "<interval> <prompt_or_command>",
        "Run a prompt on a recurring interval (e.g. loop 5m \"check status\")",
        CommandGroup::Jobs,
        false,
        false,
        false,
    ),
];
