use super::{CommandGroup, CommandSpec, spec};

pub const COMMANDS: &[CommandSpec] = &[
    spec(
        "launch",
        "[--headless]",
        "Launch Chrome and start a session",
        CommandGroup::Browser,
        false,
        false,
        false,
    ),
    spec(
        "connect",
        "",
        "Attach to already-running Chrome (no launch)",
        CommandGroup::Browser,
        false,
        false,
        false,
    ),
    spec(
        "navigate",
        "<url>",
        "Navigate to URL",
        CommandGroup::Browser,
        true,
        true,
        true,
    ),
    spec(
        "back",
        "",
        "Go back in history",
        CommandGroup::Browser,
        true,
        true,
        false,
    ),
    spec(
        "forward",
        "",
        "Go forward in history",
        CommandGroup::Browser,
        true,
        true,
        false,
    ),
    spec(
        "reload",
        "",
        "Reload the current page",
        CommandGroup::Browser,
        true,
        true,
        false,
    ),
    spec(
        "tabs",
        "",
        "List tabs owned by this session",
        CommandGroup::Browser,
        true,
        false,
        true,
    ),
    spec(
        "tab",
        "<id>",
        "Switch to a session-owned tab",
        CommandGroup::Browser,
        true,
        false,
        false,
    ),
    spec(
        "new-tab",
        "[url]",
        "Open a new tab in this session",
        CommandGroup::Browser,
        true,
        true,
        true,
    ),
    spec(
        "close",
        "",
        "Close current tab",
        CommandGroup::Browser,
        true,
        false,
        true,
    ),
    spec(
        "activate",
        "",
        "Bring browser window to front (macOS)",
        CommandGroup::Browser,
        true,
        false,
        false,
    ),
    spec(
        "minimize",
        "",
        "Minimize browser window (macOS)",
        CommandGroup::Browser,
        true,
        false,
        false,
    ),
    spec(
        "kill",
        "",
        "Kill custom profile browser session",
        CommandGroup::Browser,
        true,
        false,
        false,
    ),
    spec(
        "frames",
        "",
        "List frames/iframes",
        CommandGroup::Browser,
        true,
        true,
        false,
    ),
    spec(
        "frame",
        "<id|sel>",
        "Switch frame (frame main to reset)",
        CommandGroup::Browser,
        true,
        true,
        false,
    ),
    spec(
        "read",
        "[selector]",
        "Reader-mode text extraction",
        CommandGroup::Page,
        true,
        true,
        true,
    ),
    spec(
        "text",
        "[selector]",
        "Full page text with interactive refs",
        CommandGroup::Page,
        true,
        true,
        false,
    ),
    spec(
        "dom",
        "[selector]",
        "Get compact DOM (--tokens=N to limit output)",
        CommandGroup::Page,
        true,
        true,
        false,
    ),
    spec(
        "ax-tree",
        "[selector]",
        "Get accessibility tree",
        CommandGroup::Page,
        true,
        true,
        true,
    ),
    spec(
        "observe",
        "",
        "Show interactive elements as ready-to-use commands",
        CommandGroup::Page,
        true,
        true,
        false,
    ),
    spec(
        "find",
        "<query>",
        "Find element by description",
        CommandGroup::Page,
        true,
        true,
        false,
    ),
    spec(
        "resolve",
        "<selector>",
        "Get link target URL without clicking",
        CommandGroup::Page,
        true,
        true,
        false,
    ),
    spec(
        "screenshot",
        "[--full]",
        "Capture screenshot (--full for entire page)",
        CommandGroup::Page,
        true,
        true,
        true,
    ),
    spec(
        "pdf",
        "[path]",
        "Save page as PDF",
        CommandGroup::Page,
        true,
        true,
        false,
    ),
    spec(
        "search",
        "<query>",
        "Search the web in-browser and extract results",
        CommandGroup::Page,
        true,
        true,
        false,
    ),
    spec(
        "read-urls",
        "<url1> <url2> ...",
        "Read multiple URLs in parallel",
        CommandGroup::Page,
        true,
        true,
        false,
    ),
    spec(
        "grid",
        "[spec]",
        "Overlay coordinate grid (8x6, 50, off)",
        CommandGroup::Page,
        true,
        true,
        false,
    ),
    spec(
        "batch",
        "'<json>'",
        "Execute multiple actions sequentially",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "click",
        "<sel|x,y|--text>",
        "Click element, coordinates, or text match",
        CommandGroup::Interact,
        true,
        true,
        true,
    ),
    spec(
        "hover",
        "<sel|x,y|--text>",
        "Hover",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "focus",
        "<selector>",
        "Focus an element without clicking",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "clear",
        "<selector>",
        "Clear an input or contenteditable",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "type",
        "<sel> <text>",
        "Type text into element",
        CommandGroup::Interact,
        true,
        true,
        true,
    ),
    spec(
        "fill",
        "<sel1> <val1> [sel2] [val2] ...",
        "Fill multiple fields",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "keyboard",
        "<text>",
        "Type at current caret position",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "paste",
        "<text>",
        "Paste text via ClipboardEvent",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "clipboard",
        "--html <html> [--text <text>]",
        "Paste rich HTML",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "insert-text",
        "<text>",
        "Insert text at cursor via CDP Input.insertText",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "select",
        "<sel> <val>",
        "Select option(s) from a <select>",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "upload",
        "<sel> <file>",
        "Upload file(s) to a file input",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "drag",
        "<from> <to>",
        "Drag from one element to another",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "dialog",
        "<accept|dismiss> [text]",
        "Handle next dialog",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "wait-for",
        "<sel> [ms]",
        "Wait for element to appear",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "wait-for-nav",
        "[ms]",
        "Wait for navigation/readystate",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "press",
        "<key>",
        "Press key or combo (Enter, Ctrl+A, Meta+C)",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "scroll",
        "<...>",
        "Scroll page or element",
        CommandGroup::Interact,
        true,
        true,
        true,
    ),
    spec(
        "eval",
        "<js>",
        "Evaluate JavaScript",
        CommandGroup::Interact,
        true,
        true,
        true,
    ),
    spec(
        "media",
        "<dark|light|...>",
        "Emulate media features (dark mode, print, etc)",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "animations",
        "<pause|resume>",
        "Pause/resume page animations",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "zoom",
        "<in|out|N>",
        "Zoom page (25-200%, preserves layout)",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "lock",
        "[seconds]",
        "Lock active tab for exclusive access",
        CommandGroup::Interact,
        true,
        false,
        false,
    ),
    spec(
        "unlock",
        "",
        "Release tab lock",
        CommandGroup::Interact,
        true,
        false,
        false,
    ),
    spec(
        "cookies",
        "...",
        "Manage cookies",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "console",
        "...",
        "Show/listen for console logs",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "network",
        "...",
        "Capture/show network requests",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "block",
        "...",
        "Configure request blocking",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "viewport",
        "...",
        "Set viewport preset or dimensions",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "download",
        "...",
        "Configure/list downloads",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "storage",
        "<get|set|remove|clear>",
        "Manage localStorage/sessionStorage",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "service-workers",
        "<list|unregister|update>",
        "Manage service workers",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "security",
        "<ignore-certs|strict>",
        "Control certificate validation",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "geo",
        "<lat> <lng> [accuracy] | off",
        "Emulate geolocation",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "mouse",
        "<move|down|up|wheel> [args]",
        "Raw mouse primitives",
        CommandGroup::Interact,
        true,
        true,
        false,
    ),
    spec(
        "state",
        "<save|load> [path]",
        "Save/load cookies + storage to portable JSON",
        CommandGroup::Data,
        true,
        true,
        false,
    ),
    spec(
        "auth",
        "<save|login|list|delete> [args]",
        "Credential vault + auto-fill login forms",
        CommandGroup::Data,
        false,
        false,
        false,
    ),
    spec(
        "screencast",
        "<start|stop|frame> [opts]",
        "Live screen capture (start/stop/get frames)",
        CommandGroup::Browser,
        true,
        true,
        false,
    ),
    spec(
        "desktop",
        "<subcommand> [args]",
        "Desktop automation subcommands",
        CommandGroup::Desktop,
        false,
        false,
        false,
    ),
    spec(
        "browser-sessions",
        "<list|show>",
        "List or inspect explicit local browser sessions",
        CommandGroup::Browser,
        false,
        false,
        false,
    ),
];
