use super::{CommandGroup, CommandSpec, spec, spec_aliases};

pub const COMMANDS: &[CommandSpec] = &[
    spec(
        "pack",
        "[path|-] [--from=json|yaml|csv]",
        "Pack JSON, YAML, or CSV into a compact text format",
        CommandGroup::Data,
        false,
        false,
        false,
    ),
    spec(
        "unpack",
        "[path|-] [--to=json|yaml|csv]",
        "Restore packed text to JSON, YAML, or CSV",
        CommandGroup::Data,
        false,
        false,
        false,
    ),
    spec_aliases(
        "symbols",
        "<path> [--imports]",
        "List symbols (functions, structs, classes) in file or directory",
        CommandGroup::Code,
        &["syms"],
        false,
        false,
        false,
    ),
    spec_aliases(
        "definition",
        "<name> [path]",
        "Find and show a symbol's full definition",
        CommandGroup::Code,
        &["def"],
        false,
        false,
        false,
    ),
    spec_aliases(
        "references",
        "<name> [path]",
        "Find all usage sites of a symbol",
        CommandGroup::Code,
        &["refs"],
        false,
        false,
        false,
    ),
    spec(
        "structure",
        "[path]",
        "Hierarchical symbol tree for a project or file",
        CommandGroup::Code,
        false,
        false,
        false,
    ),
    spec(
        "doc",
        "<outline|section|search|map> [args]",
        "Markdown document intelligence (outline, sections, search)",
        CommandGroup::Code,
        false,
        false,
        false,
    ),
];
