use super::{CommandGroup, CommandSpec, spec};

pub const COMMANDS: &[CommandSpec] = &[
    spec(
        "daemon",
        "[start|stop|restart|status]",
        "Manage the Sidekar background daemon",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "config",
        "list|get|set|reset",
        "View or change settings",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "prompt",
        "list|get|set|edit|reset|diff [key] [text|--file=path]",
        "View or edit the agent prompts stored in SQLite",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "event",
        "<list|clear> [--level=error|debug|info] [N|--limit=N]",
        "View or clear the local event log",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "update",
        "",
        "Check for updates and self-update",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "install",
        "",
        "Install skill file for detected agents (optional config-folder hint)",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "uninstall",
        "",
        "Remove sidekar data and skill files",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "skill",
        "",
        "Print SKILL.md to stdout",
        CommandGroup::System,
        false,
        false,
        false,
    ),
];
