use super::{CommandGroup, CommandSpec, spec};

pub const COMMANDS: &[CommandSpec] = &[
    spec(
        "run",
        "<sessionId> [command args...]",
        "Run a command or command file against an explicit browser session",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "daemon",
        "[start|stop|restart|status]",
        "Manage the Sidekar background daemon",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "config",
        "list|get|set|reset",
        "View or change settings",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "feedback",
        "<rating> [comment]",
        "Send a rating and optional comment",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "event",
        "<list|clear> [--level=error|debug|info] [N]",
        "View or clear the local event log",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "update",
        "",
        "Check for updates and self-update",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "install",
        "",
        "Install skill file for detected agents",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "uninstall",
        "",
        "Remove sidekar data and skill files",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "skill",
        "",
        "Print SKILL.md to stdout",
        CommandGroup::System,
        false,
        false,
        false,
    ),
    spec(
        "ext",
        "<sub> [args]",
        "Control the browser via the extension (tabs, read, click, ...)",
        CommandGroup::System,
        false,
        false,
        false,
    ),
];
