#[cfg(target_os = "macos")]
pub mod bg_input;
#[cfg(target_os = "macos")]
pub mod focus_guard;
#[cfg(target_os = "macos")]
pub mod input;
#[cfg(target_os = "macos")]
pub mod macos;
#[cfg(target_os = "macos")]
pub use macos as native;
#[cfg(target_os = "macos")]
pub mod monitor;
#[cfg(target_os = "macos")]
pub mod refs;
#[cfg(target_os = "macos")]
pub mod screen;
#[cfg(target_os = "macos")]
pub mod skylight;
pub mod types;
