//! Extension bridge for Chrome extension communication.
//!
//! The Chrome extension connects via localhost WebSocket, and the daemon
//! routes `sidekar ext <command>` requests to the connected extension bridge.

use anyhow::{Context, Result, anyhow, bail};
use serde_json::{Value, json};
use std::collections::{HashMap, VecDeque};
use std::fs;
use std::io::Cursor;
use std::sync::Arc;
use tokio::sync::{Mutex, mpsc, oneshot};

use crate::message::epoch_secs;

use dirs;
use zip::ZipArchive;

const DEFAULT_API_URL: &str = "https://sidekar.dev";

pub const EXTENSION_ZIP: &[u8] = include_bytes!("../assets/extension.zip");

mod cli;
mod verify;

pub use cli::send_cli_command;
pub use verify::{VerifyResult, is_ext_available, verify_ext_token};

/// Paste / cli_exec can exceed 30s (CDP attach, Google Docs focus path).
const TIMEOUT_SECS: u64 = 180;

// ---------------------------------------------------------------------------
// Shared state between server and extension connections
// ---------------------------------------------------------------------------

/// A single extension bridge connection (one per Chrome profile).
pub struct ExtConnection {
    pub bridge_tx: mpsc::UnboundedSender<String>,
    pub pending: HashMap<String, oneshot::Sender<Value>>,
    /// Extension-initiated `cli_exec` work running in the daemon (inserttext / keyboard).
    pub cli_exec_inflight: u32,
    pub verified_user_id: String,
    pub last_contact: u64,
    pub owner_agent_id: Option<String>,
    /// Stable per-Chrome-profile UUID generated by the extension on first run
    /// and persisted in chrome.storage.local (scoped to the user-data-dir
    /// profile). Empty for pre-install-id extensions; falls back to short
    /// browser tag in that case.
    pub profile: String,
    pub browser: String,
    /// Chrome extension's manifest.json version as reported at
    /// `bridge_register`. None for pre-version-reporting extensions.
    /// Used by diagnostics to surface extension/daemon version drift
    /// — Chrome auto-updates the extension independently of the
    /// binary, so mismatches happen and can change the wire protocol
    /// semantics silently. `ext status` surfaces this field so
    /// drift is visible.
    pub ext_version: Option<String>,
}

/// A registered DOM watcher. Watch events are delivered via broker to `deliver_to`.
pub struct WatchRecord {
    pub watch_id: String,
    pub selector: String,
    pub deliver_to: String,
    pub conn_id: u64,
    pub profile: String,
    pub created_at: u64,
}

/// A single passive-network event as received from the extension. The extension
/// has already capped body previews (~64 KiB) and stripped sensitive header
/// keys; daemon-side treatment is storage + retrieval only.
#[derive(Clone)]
pub struct PassiveNetEvent {
    pub conn_id: u64,
    pub profile: String,
    pub received_at: u64,
    pub tab_id: Option<i64>,
    pub tab_url: String,
    pub frame_url: String,
    /// `net | sse | sse_done | sse_open | sse_error` — forwarded from
    /// content.js verbatim.
    pub kind: String,
    /// Full detail payload for the single event.
    pub detail: Value,
}

/// Bounded ring of passive-network events per connection.
pub struct PassiveNetRing {
    cap: usize,
    events: VecDeque<PassiveNetEvent>,
    total_received: u64,
    total_dropped: u64,
}

impl PassiveNetRing {
    pub fn new(cap: usize) -> Self {
        Self {
            cap,
            events: VecDeque::with_capacity(cap.min(4096)),
            total_received: 0,
            total_dropped: 0,
        }
    }

    pub fn push(&mut self, evt: PassiveNetEvent) {
        while self.events.len() >= self.cap {
            self.events.pop_front();
            self.total_dropped = self.total_dropped.saturating_add(1);
        }
        self.events.push_back(evt);
        self.total_received = self.total_received.saturating_add(1);
    }

    pub fn len(&self) -> usize {
        self.events.len()
    }

    pub fn total_received(&self) -> u64 {
        self.total_received
    }

    pub fn total_dropped(&self) -> u64 {
        self.total_dropped
    }

    pub fn iter(&self) -> impl Iterator<Item = &PassiveNetEvent> {
        self.events.iter()
    }

    pub fn clear(&mut self) {
        self.events.clear();
    }
}

pub struct ExtState {
    pub connections: HashMap<u64, ExtConnection>,
    pub next_connection_id: u64,
    pub watches: HashMap<String, WatchRecord>,
    /// Per-connection passive-network firehose rings. Not a request/response
    /// pending map — pure push-from-extension path with bounded storage.
    pub passive_rings: HashMap<u64, PassiveNetRing>,
    pub passive_ring_cap: usize,
}

impl Default for ExtState {
    fn default() -> Self {
        Self {
            connections: HashMap::new(),
            next_connection_id: 1,
            watches: HashMap::new(),
            passive_rings: HashMap::new(),
            passive_ring_cap: 2000,
        }
    }
}

pub type SharedExtState = Arc<Mutex<ExtState>>;

fn ext_api_base() -> String {
    std::env::var("SIDEKAR_API_URL").unwrap_or_else(|_| DEFAULT_API_URL.to_string())
}

type SharedState = Arc<Mutex<ExtState>>;

// ---------------------------------------------------------------------------
// Ext bridge for daemon
// ---------------------------------------------------------------------------

/// Disconnect a specific bridge connection by id.
pub async fn disconnect_bridge_by_id(state: &SharedExtState, connection_id: u64) {
    disconnect_bridge(state, connection_id).await;
}

async fn disconnect_bridge(state: &SharedState, connection_id: u64) {
    let pending = {
        let mut s = state.lock().await;
        // Remove watches owned by this connection
        s.watches.retain(|_, w| w.conn_id != connection_id);
        match s.connections.remove(&connection_id) {
            Some(conn) => conn.pending,
            None => return,
        }
    };
    for (_id, tx) in pending {
        let _ = tx.send(json!({"error": "Extension disconnected"}));
    }
}

/// Register a watch record after the extension confirms setup.
pub async fn register_watch(
    state: &SharedExtState,
    watch_id: String,
    selector: String,
    deliver_to: String,
    conn_id: u64,
    profile: String,
) {
    let mut s = state.lock().await;
    s.watches.insert(
        watch_id.clone(),
        WatchRecord {
            watch_id,
            selector,
            deliver_to,
            conn_id,
            profile,
            created_at: epoch_secs(),
        },
    );
}

/// Remove a watch record (called on unwatch or connection drop).
pub async fn remove_watch(state: &SharedExtState, watch_id: &str) -> Option<WatchRecord> {
    let mut s = state.lock().await;
    s.watches.remove(watch_id)
}

/// Drop watches whose owning connection is gone or that have exceeded
/// `max_age_secs`. Guards against zombie watches from silently-dropped
/// extension connections and forgotten registrations on long daemon uptime.
pub async fn sweep_stale_watches(state: &SharedExtState, max_age_secs: u64) -> usize {
    let mut s = state.lock().await;
    let now = epoch_secs();
    let before = s.watches.len();
    let live_conns: std::collections::HashSet<u64> = s.connections.keys().copied().collect();
    s.watches.retain(|_, w| {
        live_conns.contains(&w.conn_id) && now.saturating_sub(w.created_at) <= max_age_secs
    });
    before - s.watches.len()
}

/// Look up delivery target for a watch event.
pub async fn find_watch_target(state: &SharedExtState, watch_id: &str) -> Option<(String, String)> {
    let s = state.lock().await;
    s.watches
        .get(watch_id)
        .map(|w| (w.deliver_to.clone(), w.selector.clone()))
}

/// Get all active watches for status display.
pub async fn list_watches(state: &SharedExtState) -> Vec<Value> {
    let s = state.lock().await;
    s.watches
        .values()
        .map(|w| {
            json!({
                "watchId": w.watch_id,
                "selector": w.selector,
                "deliverTo": w.deliver_to,
                "profile": w.profile,
                "createdAt": w.created_at,
            })
        })
        .collect()
}

/// Deliver a watch event via the broker to the registered agent.
pub async fn deliver_watch_event(
    state: &SharedExtState,
    watch_id: &str,
    current: &str,
    previous: &str,
    url: Option<&str>,
) -> Result<()> {
    let (deliver_to, selector) = match find_watch_target(state, watch_id).await {
        Some(v) => v,
        None => return Ok(()), // watch was removed; drop event
    };

    let mut message = format!("Element changed on {selector}");
    if let Some(u) = url
        && !u.is_empty()
    {
        message.push_str(&format!("\nURL: {u}"));
    }
    if !previous.is_empty() {
        let prev_trim = if previous.len() > 500 {
            &previous[..500]
        } else {
            previous
        };
        message.push_str(&format!("\nBefore: {prev_trim}"));
    }
    if !current.is_empty() {
        let cur_trim = if current.len() > 500 {
            &current[..500]
        } else {
            current
        };
        message.push_str(&format!("\nAfter: {cur_trim}"));
    }

    let formatted = format!("[from sidekar-ext-watch]: {message}");
    crate::broker::enqueue_message("sidekar-ext-watch", &deliver_to, &formatted)?;
    Ok(())
}

/// Register a new bridge connection and return the connection_id and bridge_rx.
/// Used by the WebSocket path in daemon.rs.
pub async fn register_bridge_ws(
    state: &SharedExtState,
    user_id: String,
    agent_id: Option<String>,
    browser: String,
    install_id: String,
    ext_version: Option<String>,
) -> (u64, mpsc::UnboundedReceiver<String>, String) {
    let now = epoch_secs();
    let (bridge_tx, bridge_rx) = mpsc::unbounded_channel::<String>();
    let mut s = state.lock().await;
    let cid = s.next_connection_id;
    s.next_connection_id = cid.wrapping_add(1);
    // Prefer the extension-provided install_id (stable per Chrome profile).
    // Fall back to lowercased browser name for pre-install-id extensions so
    // older installs still show *something*.
    let profile = if install_id.is_empty() {
        browser.to_lowercase()
    } else {
        install_id
    };
    s.connections.insert(
        cid,
        ExtConnection {
            bridge_tx,
            pending: HashMap::new(),
            cli_exec_inflight: 0,
            verified_user_id: user_id,
            last_contact: now,
            owner_agent_id: agent_id,
            profile: profile.clone(),
            browser,
            ext_version,
        },
    );
    (cid, bridge_rx, profile)
}

/// Ingest a passive-network firehose frame from the extension. The extension
/// sends one frame containing a batch of `events`; each is unpacked into the
/// per-connection ring.
///
/// This path deliberately bypasses the request/response pending map — passive
/// capture is push-only and bounded at the daemon by `passive_ring_cap`.
pub async fn ingest_passive_firehose(
    state: &SharedExtState,
    connection_id: u64,
    tab_id: Option<i64>,
    tab_url: String,
    frame_url: String,
    events: Vec<Value>,
    extension_dropped: u64,
) {
    let now = epoch_secs();
    let mut s = state.lock().await;
    let profile = match s.connections.get(&connection_id) {
        Some(c) => c.profile.clone(),
        None => return, // connection gone; drop
    };
    let cap = s.passive_ring_cap;
    let ring = s
        .passive_rings
        .entry(connection_id)
        .or_insert_with(|| PassiveNetRing::new(cap));
    if extension_dropped > 0 {
        ring.total_dropped = ring.total_dropped.saturating_add(extension_dropped);
    }
    for evt in events {
        let kind = evt
            .get("kind")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let detail = evt.get("detail").cloned().unwrap_or(Value::Null);
        if kind.is_empty() {
            continue;
        }
        ring.push(PassiveNetEvent {
            conn_id: connection_id,
            profile: profile.clone(),
            received_at: now,
            tab_id,
            tab_url: tab_url.clone(),
            frame_url: frame_url.clone(),
            kind,
            detail,
        });
    }
}

/// Snapshot the passive-net ring for a connection. `limit` caps the returned
/// slice (most recent events last).
pub async fn passive_snapshot(
    state: &SharedExtState,
    connection_id: u64,
    limit: Option<usize>,
) -> Vec<Value> {
    let s = state.lock().await;
    let Some(ring) = s.passive_rings.get(&connection_id) else {
        return Vec::new();
    };
    let take = limit.unwrap_or(ring.len()).min(ring.len());
    let skip = ring.len().saturating_sub(take);
    ring.iter()
        .skip(skip)
        .map(|e| {
            json!({
                "kind": e.kind,
                "receivedAt": e.received_at,
                "tabId": e.tab_id,
                "tabUrl": e.tab_url,
                "frameUrl": e.frame_url,
                "source": "passive",
                "detail": e.detail,
            })
        })
        .collect()
}

pub async fn passive_clear(state: &SharedExtState, connection_id: u64) -> usize {
    let mut s = state.lock().await;
    match s.passive_rings.get_mut(&connection_id) {
        Some(ring) => {
            let n = ring.len();
            ring.clear();
            n
        }
        None => 0,
    }
}

pub async fn passive_stats(state: &SharedExtState, connection_id: u64) -> Value {
    let s = state.lock().await;
    match s.passive_rings.get(&connection_id) {
        Some(ring) => json!({
            "connected": true,
            "pending": ring.len(),
            "cap": s.passive_ring_cap,
            "totalReceived": ring.total_received(),
            "totalDropped": ring.total_dropped(),
        }),
        None => json!({
            "connected": false,
            "pending": 0,
            "cap": s.passive_ring_cap,
            "totalReceived": 0,
            "totalDropped": 0,
        }),
    }
}

/// Update last_contact for a connection.
pub async fn touch_connection(state: &SharedExtState, connection_id: u64) {
    let mut s = state.lock().await;
    if let Some(conn) = s.connections.get_mut(&connection_id) {
        conn.last_contact = epoch_secs();
    }
}

pub async fn cli_exec_begin(state: &SharedExtState, connection_id: u64) {
    let mut s = state.lock().await;
    if let Some(conn) = s.connections.get_mut(&connection_id) {
        conn.cli_exec_inflight = conn.cli_exec_inflight.saturating_add(1);
    }
}

pub async fn cli_exec_end(state: &SharedExtState, connection_id: u64) {
    let mut s = state.lock().await;
    if let Some(conn) = s.connections.get_mut(&connection_id) {
        conn.cli_exec_inflight = conn.cli_exec_inflight.saturating_sub(1);
        conn.last_contact = epoch_secs();
    }
}

/// Route an inbound response (by id) to the correct pending oneshot.
pub async fn resolve_pending(state: &SharedExtState, connection_id: u64, val: Value) {
    if let Some(id) = val.get("id").and_then(|v| v.as_str()) {
        let mut s = state.lock().await;
        if let Some(conn) = s.connections.get_mut(&connection_id)
            && let Some(tx) = conn.pending.remove(id)
        {
            let _ = tx.send(val);
        }
    }
}

/// Send a command to the extension via the shared state.
/// Used by daemon to forward ext commands from unix socket.
pub struct RoutedCommandResult {
    pub response: Value,
    pub conn_id: u64,
    pub profile: String,
}

pub async fn forward_command(
    state: &SharedExtState,
    command: Value,
    agent_id: Option<String>,
    target_conn: Option<u64>,
    target_profile: Option<String>,
) -> Result<RoutedCommandResult> {
    send_command(
        state,
        command,
        agent_id.as_deref(),
        target_conn,
        target_profile.as_deref(),
    )
    .await
}

/// Get extension connection status.
pub async fn get_status(state: &SharedExtState) -> Value {
    let s = state.lock().await;
    let count = s.connections.len();
    let connected = count > 0;
    let details: Vec<Value> = s
        .connections
        .iter()
        .map(|(id, c)| {
            json!({
                "id": id,
                "profile": c.profile,
                "browser": c.browser,
                "user_id": c.verified_user_id,
                "owner": c.owner_agent_id,
                // Surface the extension's reported manifest version
                // and whether it drifts from the daemon binary, so
                // `sidekar ext status` immediately shows a mismatch
                // without anyone having to grep logs.
                "ext_version": c.ext_version,
                "version_matches_daemon": c
                    .ext_version
                    .as_deref()
                    .map(|v| v == env!("CARGO_PKG_VERSION")),
            })
        })
        .collect();
    json!({
        "connected": connected,
        "authenticated": connected,
        "connections": details,
    })
}

/// Pick a connection and send a command.
/// Priority: target_conn > target_profile > single available connection.
async fn send_command(
    state: &SharedState,
    command: Value,
    _agent_id: Option<&str>,
    target_conn: Option<u64>,
    target_profile: Option<&str>,
) -> Result<RoutedCommandResult> {
    let id = format!("{:08x}", rand::random::<u32>());
    let mut msg = command;
    msg.as_object_mut().unwrap().insert("id".into(), json!(id));

    let (tx, rx) = oneshot::channel();
    let (conn_id, profile) = {
        let mut s = state.lock().await;
        if s.connections.is_empty() {
            bail!("Extension not connected. Is Chrome running with the Sidekar extension?");
        }

        let conn_id = if let Some(cid) = target_conn {
            // Explicit connection ID
            if !s.connections.contains_key(&cid) {
                bail!("Connection {cid} not found. Use `sidekar ext status` to list connections.");
            }
            cid
        } else if let Some(profile) = target_profile {
            // Match by profile name (case-insensitive substring)
            let lp = profile.to_lowercase();
            let found = s
                .connections
                .iter()
                .find(|(_, c)| c.profile.to_lowercase().contains(&lp))
                .map(|(id, _)| *id);
            match found {
                Some(cid) => cid,
                None => bail!(
                    "No connection matching profile '{profile}'. Use `sidekar ext status` to list."
                ),
            }
        } else if s.connections.len() == 1 {
            *s.connections.keys().next().unwrap()
        } else {
            bail!(
                "Multiple extension connections are available. Rerun with `--conn` or `--profile`."
            );
        };

        let conn = s.connections.get_mut(&conn_id).unwrap();
        let profile = conn.profile.clone();
        conn.pending.insert(id.clone(), tx);
        let text = serde_json::to_string(&msg)?;
        if conn.bridge_tx.send(text).is_err() {
            conn.pending.remove(&id);
            bail!("Failed to send to extension bridge");
        }
        (conn_id, profile)
    };

    match tokio::time::timeout(std::time::Duration::from_secs(TIMEOUT_SECS), rx).await {
        Ok(Ok(val)) => Ok(RoutedCommandResult {
            response: val,
            conn_id,
            profile,
        }),
        Ok(Err(_)) => bail!("Extension response channel closed"),
        Err(_) => {
            let mut s = state.lock().await;
            if let Some(conn) = s.connections.get_mut(&conn_id) {
                conn.pending.remove(&id);
            }
            bail!("Extension command timed out ({TIMEOUT_SECS}s)")
        }
    }
}
