mod extract;
mod page;

pub use extract::*;
pub use page::*;

pub const ADBLOCK_PATTERNS: &[&str] = &[
    "google-analytics.com",
    "googletagmanager.com",
    "googletagservices.com",
    "googlesyndication.com",
    "googleadservices.com",
    "doubleclick.net",
    "facebook.com/tr",
    "connect.facebook.net",
    "fbevents.js",
    "analytics.twitter.com",
    "ads-twitter.com",
    "segment.io",
    "segment.com",
    "mixpanel.com",
    "amplitude.com",
    "hotjar.com",
    "fullstory.com",
    "heapanalytics.com",
    "mouseflow.com",
    "crazyegg.com",
    "newrelic.com",
    "nr-data.net",
    "adnxs.com",
    "openx.net",
    "pubmatic.com",
    "rubiconproject.com",
    "amazon-adsystem.com",
    "criteo.com",
    "criteo.net",
    "taboola.com",
    "outbrain.com",
    "revcontent.com",
    "marketo.com",
    "marketo.net",
    "pardot.com",
    "cookielaw.org",
    "cookiebot.com",
    "onetrust.com",
    "trustarc.com",
    "scorecardresearch.com",
    "quantserve.com",
    "chartbeat.com",
    "optimizely.com",
    "demdex.net",
    "addthis.com",
    "sharethis.com",
];
